### ISSUE TITLE
shell_execute Stucks in docker.

### ISSUE THREAD

**Issue by Adel-Magebinary** [GUI/lua-resty-auto-ssl#51]
I'm running this from a docker centos 7 image. It somehow stucks on lets_encrypt.lua 

   status, out, err = shell_execute(command)

   env HOOK_SECRET=2f9506c7a8adca5e3ec26ee5088124e297868bf2e5811b1a6fce97df216a4e91 HOOK_SERVER_PORT=8999 /usr/local/openresty/luajit/share/lua/5.1/resty/auto-ssl/shell/letsencrypt_hooks deploy_cert test55.XXX.com /tmp/letsencrypt/certs/test55.XXX.com/privkey.pem /tmp/letsencrypt/certs/test55.XXX.com/cert.pem /tmp/letsencrypt/certs/test55.XXX.com/fullchain.pem /tmp/letsencrypt/certs/test55.XXX.com/chain.pem 1489127206

I have tried to execute the command variable manually on bash. It runs all okey.

I also have tried to execute    status, out, err = shell_execute('ls -lah') to see if things are working correctly. It does execute from lua no problem. 

Error log
2017/03/10 06:54:46 [warn] 78012#78012: *371 [lua] lets_encrypt.lua:52: issue_cert(): auto-ssl: dehydrated succeeded, but certs still missing from storage - trying to manually copy - domain: test66.xxx.com, context: ssl_certificate_by_lua*, client: , server: 0.0.0.0:443

2017/03/10 06:54:40 [error] 78012#78012: *363 [lua] ssl_certificate.lua:247: auto-ssl: could not get certificate for  - using fallback - failed to get or issue certificate, context: ssl_certificate_by_lua*, client: , server: 0.0.0.0:443

Any ideas guys? I'm running everything as the latest.

**Comment by Adel-Magebinary** [comment]
I finally got this sorted. The shell socket somehow stucks on the letsencrypt_hooks deploy_cert function when FULLCHAIN content is added into curl. I can't dig out why and the shell just hangs forver. There's probably socket size limit somewhere in my container? I got this fixed by mentioning file name directly in curl. Will submit a pull request soon.

**Comment by Adel-Magebinary** [comment]
BTW, you should be able to replicate the issue in your docker or joyent based containers.

**Comment by Adel-Magebinary** [comment]
@GUI

**Comment by GUI** [comment]
#53 is merged, so while I'm still not entirely sure of why this was happening in your environment, it should hopefully be fixed. Thanks again for the fix and improvements!
